### PR TITLE
Add Tablist buffering

### PR DESCRIPTION
**Pull request by JustAlittleWolf**
Useful for servers with big/complicated tablists like mccisland (boosts fps from 150 to 300 when pressing tab for me)

### CODE REVIEW

**Comment by tr7zw** [comment]
Oh neat cool. Yeah, I was going to do the other missing UI components like tab/boss bar once I'm done fixing other issues like the name buffering/signs and refactoring some logic to work for a Forge port. But this will speed it up, will probably make a release tomorrow or so to include this and the sign fixes.

**Comment by JustAlittleWolf** [comment]
Oh nice thanks. Also I haven't tested a lot so there might be some issues.

**Comment by tr7zw** [comment]
The entire 1.20 version is wonky at best, so not an issue. Now if only people would read the release notes 😅

**Comment by tr7zw** [comment]
Hm this will need some work down the line, the health indicator got stuck like this. But that's a rather small issue, so whatever, at least it proves the code works 😅.
grafik

**Pull request merged**
