### PR TITLE
Update to 1.20.4

### PR DESCRIPTION
**Pull request by rybot666**
This PR updates Exordium to be compatible with 1.20.4

### CODE REVIEW

**Comment by tr7zw** [comment]
🤯 You are crazy 😅. I'll have to check it out later, since you used a different formatter(or maybe this project didn't have one setup yet), checking all 35 will take me a moment. If it's all fine and working I'll release it later today. Also, contact me on Discord (if you want).

**Comment by tr7zw** [comment]
Seems all good. Just realized that the formatted got introduced after the last change to the mod, that's why so much changed. The Forge version is broken as in 1.20.2, so I'll disable that part for the release.

**Comment by R00tB33rMan** [comment]
Ah yes, I decided to push someone to assist me with this mod's upgrade. Your mod is fantastic and I don't want to see it die :(

**Comment by tr7zw** [comment]
It's less die, I was just too unmotivated to sink much time into it, after the Forge version was a fail(hotbar doesn't update), and all the other compatibility issues with other mods. Additionally, in 1.20.5 Mojang reworked the UI logic to be less of a mess(but also requiring another rewrite of the core logic), so I was at a low point with this mod.

**Comment by R00tB33rMan** [comment]
> It's less die, I was just too unmotivated to sink much time into it, after the Forge version was a fail(hotbar doesn't update), and all the other compatibility issues with other mods. Additionally, in 1.20.5 Mojang reworked the UI logic to be less of a mess(but also requiring another rewrite of the core logic), so I was at a low point with this mod.

That's fully understandable. I'd be happy to pull the same person or another contributor in to assist with this huge shift. I have a lot of people under my belt/available for contact and love using this mod to keep my game running smooth.

**Pull request merged**
